---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: redhat.satellite
    version: 2.2.0
  - name: redhat.satellite_operations
    version: 0.3.2
  - name: redhat.insights
    version: 1.0.5
